Repository codestates-seb/seb40_main_023, pull requests merged in 2022-11, with the labels that each got.

#12 [Feat] 이미지 추가 및 tailwind config 수정
  client/pages/main.tsx
  client/public/dummy/mypage-profile.png
  client/public/dummy/review-profile.png
  client/public/dummy/user1.png
  client/public/dummy/user2.png
  client/public/dummy/user3.png
  client/public/images/char/char-404.svg
  client/public/images/char/char-banner.svg
  client/public/images/char/char-button1.svg
  client/public/images/char/char-button2.svg
  client/public/images/char/char-footer.svg
  client/public/images/content/ico-capture.svg
  client/public/images/content/ico-mg-money.svg
  client/public/images/content/ico-sound-off.svg
  client/public/images/content/ico-sound-on.svg
  client/public/images/content/ico-upload-image.svg
  client/public/images/content/img-basket.svg
  client/public/images/content/img-bok1-1.svg
  client/public/images/content/img-bok1-2.svg
  client/public/images/content/img-bok1-3.svg
  client/public/images/content/img-bok1-4.svg
  client/public/images/content/img-bok1-5.svg
  client/public/images/content/img-bok2-1.svg
  client/public/images/content/img-bok2-2.svg
  client/public/images/content/img-bok2-3.svg
  client/public/images/content/img-bok2-4.svg
  client/public/images/content/img-bok2-5.svg
  client/public/images/content/img-bok3-1.svg
  client/public/images/content/img-bok3-2.svg
  client/public/images/content/img-bok3-3.svg
  client/public/images/content/img-bok3-4.svg
  client/public/images/content/img-bok3-5.svg
  client/public/images/content/img-letter.png
  client/public/images/content/pt-dots.png
  client/public/images/ico/ico-banner-arrow.svg
  client/public/images/ico/ico-card-delete.svg
  client/public/images/ico/ico-card-edit.svg
  client/public/images/ico/ico-card-qr.svg
  client/public/images/ico/ico-card-url.svg
  client/public/images/ico/ico-github.svg
  client/public/images/ico/ico-modal-close.svg
  client/public/images/ico/ico-mypage-edit.svg
  client/public/images/ico/ico-mypage-previous.svg
  client/public/images/ico/ico-profile.svg
  client/public/images/ico/ico-share-kakao.svg
  client/public/images/ico/ico-share-qr.svg
  client/public/images/ico/ico-share-url.svg
  client/public/images/ico/ico-share.svg
  client/public/images/ico/logo.svg
  client/public/vercel.svg
  client/styles/globals.css
  client/tailwind.config.js
Labels: FE

#15 [feat]복망고,리뷰 CRUD 구현
  server/build.gradle
  server/src/main/java/seb40/main023/server/exception/BusinessLogicException.java
  server/src/main/java/seb40/main023/server/exception/DataNotFoundException.java
  server/src/main/java/seb40/main023/server/exception/ExceptionCode.java
  server/src/main/java/seb40/main023/server/luckMango/controller/LuckMangoController.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoPatchDto.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoPostDto.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoResponseDto.java
  server/src/main/java/seb40/main023/server/luckMango/entity/LuckMango.java
  server/src/main/java/seb40/main023/server/luckMango/mapper/LuckMangoMapper.java
  server/src/main/java/seb40/main023/server/luckMango/repository/LuckMangoRepository.java
  server/src/main/java/seb40/main023/server/luckMango/service/LuckMangoService.java
  server/src/main/java/seb40/main023/server/member/entity/Member.java
  server/src/main/java/seb40/main023/server/response/ErrorResponse.java
  server/src/main/java/seb40/main023/server/response/MultiResponseDto.java
  server/src/main/java/seb40/main023/server/response/PageInfo.java
  server/src/main/java/seb40/main023/server/response/SingleResponseDto.java
  server/src/main/java/seb40/main023/server/review/controller/ReviewController.java
  server/src/main/java/seb40/main023/server/review/dto/ReviewPatchDto.java
  server/src/main/java/seb40/main023/server/review/dto/ReviewPostDto.java
  server/src/main/java/seb40/main023/server/review/dto/ReviewResponseDto.java
  server/src/main/java/seb40/main023/server/review/entity/Review.java
  server/src/main/java/seb40/main023/server/review/mapper/ReviewMapper.java
  server/src/main/java/seb40/main023/server/review/repository/ReviewRepository.java
  server/src/main/java/seb40/main023/server/review/service/ReviewService.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: BE

#16 [FEAT]API Member_CRUD기능구현
  server/src/main/java/seb40/main023/server/ServerApplication.java
  server/src/main/java/seb40/main023/server/audit/Auditable.java
  server/src/main/java/seb40/main023/server/luckBag/entity/LuckBag.java
  server/src/main/java/seb40/main023/server/luckMango/entity/LuckMango.java
  server/src/main/java/seb40/main023/server/member/controller/MemberController.java
  server/src/main/java/seb40/main023/server/member/dto/MemberPatchDto.java
  server/src/main/java/seb40/main023/server/member/dto/MemberPostDto.java
  server/src/main/java/seb40/main023/server/member/dto/MemberResponseDto.java
  server/src/main/java/seb40/main023/server/member/entity/Member.java
  server/src/main/java/seb40/main023/server/member/mapper/MemberMapper.java
  server/src/main/java/seb40/main023/server/member/repository/MemberRepository.java
  server/src/main/java/seb40/main023/server/member/service/MemberService.java
Labels: BE

#17 Revert "[FEAT]API Member_CRUD기능구현"
  server/src/main/java/seb40/main023/server/ServerApplication.java
  server/src/main/java/seb40/main023/server/audit/Auditable.java
  server/src/main/java/seb40/main023/server/luckBag/entity/LuckBag.java
  server/src/main/java/seb40/main023/server/luckMango/entity/LuckMango.java
  server/src/main/java/seb40/main023/server/member/controller/MemberController.java
  server/src/main/java/seb40/main023/server/member/dto/MemberPatchDto.java
  server/src/main/java/seb40/main023/server/member/dto/MemberPostDto.java
  server/src/main/java/seb40/main023/server/member/dto/MemberResponseDto.java
  server/src/main/java/seb40/main023/server/member/entity/Member.java
  server/src/main/java/seb40/main023/server/member/mapper/MemberMapper.java
  server/src/main/java/seb40/main023/server/member/repository/MemberRepository.java
  server/src/main/java/seb40/main023/server/member/service/MemberService.java
Labels: BE

#18 feat/#1 api member crud
  server/src/main/java/seb40/main023/server/ServerApplication.java
  server/src/main/java/seb40/main023/server/audit/Auditable.java
  server/src/main/java/seb40/main023/server/luckBag/entity/LuckBag.java
  server/src/main/java/seb40/main023/server/luckMango/entity/LuckMango.java
  server/src/main/java/seb40/main023/server/member/controller/MemberController.java
  server/src/main/java/seb40/main023/server/member/dto/MemberPatchDto.java
  server/src/main/java/seb40/main023/server/member/dto/MemberPostDto.java
  server/src/main/java/seb40/main023/server/member/dto/MemberResponseDto.java
  server/src/main/java/seb40/main023/server/member/entity/Member.java
  server/src/main/java/seb40/main023/server/member/mapper/MemberMapper.java
  server/src/main/java/seb40/main023/server/member/repository/MemberRepository.java
  server/src/main/java/seb40/main023/server/member/service/MemberService.java
Labels: BE

#19 Feat/#3 api luck bag
  server/.idea/misc.xml
  server/build.gradle
  server/src/main/generated/seb40/main023/server/luckBag/mapper/LuckBagMapperImpl.java
  server/src/main/java/seb40/main023/server/ServerApplication.java
  server/src/main/java/seb40/main023/server/luckBag/controller/LuckBagController.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagPatchDto.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagPostDto.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagResponseDto.java
  server/src/main/java/seb40/main023/server/luckBag/entity/LuckBag.java
  server/src/main/java/seb40/main023/server/luckBag/exception/BusinessLogicException.java
  server/src/main/java/seb40/main023/server/luckBag/exception/ExceptionCode.java
  server/src/main/java/seb40/main023/server/luckBag/mapper/LuckBagMapper.java
  server/src/main/java/seb40/main023/server/luckBag/repository/LuckBagRepository.java
  server/src/main/java/seb40/main023/server/luckBag/response/MultiResponseDto.java
  server/src/main/java/seb40/main023/server/luckBag/response/PageInfo.java
  server/src/main/java/seb40/main023/server/luckBag/response/SingleResponseDto.java
  server/src/main/java/seb40/main023/server/luckBag/service/LuckBagService.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoResponseDto.java
  server/src/main/java/seb40/main023/server/member/entity/Member.java
Labels: BE

#20 [feat] 글로벌 css 추가
  client/pages/edit/complete.tsx
  client/pages/edit/index.tsx
  client/pages/luckbag/index.tsx
  client/styles/globals.css
Labels: FE

#25 [feat]모달창 구현(상태관리 적용 후 헤더, 컨텐츠, 버튼 구조 변경 필요)
  client/components/DefaultModal.tsx
  client/pages/test.tsx
Labels: FE

#27 feat/404페이지 구현
  client/pages/failpath404.tsx
  client/pages/userDelete404.tsx
Labels: FE

#28 feat/마이페이지 구현
  client/components/BokCard.tsx
  client/components/userModify.tsx
  client/package-lock.json
  client/package.json
  client/pages/mypage.tsx
  client/pages/mypage/dummy.tsx
  client/pages/mypage/index.tsx
Labels: FE

#30 feat/메인페이지 화면 구현
  client/components/Footer.tsx
  client/components/header.tsx
  client/components/main/Chart.tsx
  client/components/main/Countdown.tsx
  client/components/main/GalleryItem.tsx
  client/components/main/ReviewItem.tsx
  client/components/main/Section.tsx
  client/components/main/SectionTitle.tsx
  client/components/main/ServiceChart.tsx
  client/components/main/ServiceGallery.tsx
  client/components/main/ServiceHowto.tsx
  client/components/main/ServiceIntro.tsx
  client/components/main/ServiceReview.tsx
  client/package-lock.json
  client/package.json
  client/pages/index.tsx
  client/public/favicon.ico
  client/public/images/char/char-button2.svg
  client/public/images/ico/ico-howto-arrow.svg
  client/store/sidebarSlice.ts
  client/styles/Home.module.css
  client/styles/globals.css
  client/tailwind.config.js
Labels: FE

#32 feat/signup page 구현
  client/pages/signup.tsx
Labels: FE

#45 feat/모달창 수정 및 마이페이지 모달창 적용
  client/components/BokCard.tsx
  client/components/DefaultModal.tsx
  client/components/Modal/DefaultModal.tsx
  client/components/userModify.tsx
  client/pages/mypage/index.tsx
  client/pages/test.tsx
  client/store/modalSlice.ts
  client/store/store.ts
Labels: FE

#50 feat/QR테스트
  client/package-lock.json
  client/package.json
  client/pages/test.tsx
Labels: FE

#51 feat/메인 차트 기능 구현
  client/components/main/chart/Chart.tsx
  client/components/main/chart/ServiceChart.tsx
  client/package-lock.json
  client/package.json
Labels: feat

#53 feat/Pretendard HS새마을체 폰트 추가
  client/components/main/SectionTitle.tsx
  client/components/main/chart/ServiceChart.tsx
  client/components/main/info/Countdown.tsx
  client/components/main/review/ServiceReview.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/index.tsx
  client/pages/lucky/index.tsx
  client/pages/lucky/login.tsx
  client/public/favicon.ico
  client/public/fonts/HSSaemaul-Regular.ttf
  client/styles/globals.css
  client/tailwind.config.js
Labels: feat, FE

#55 feat/BE Restdocs 중간 병합
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/seb40/main023/server/ServerApplication.java
  server/src/main/java/seb40/main023/server/exception/ExceptionCode.java
  server/src/main/java/seb40/main023/server/luckBag/controller/LuckBagController.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagPatchDto.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagPostDto.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagResponseDto.java
  server/src/main/java/seb40/main023/server/luckBag/entity/LuckBag.java
  server/src/main/java/seb40/main023/server/luckBag/exception/BusinessLogicException.java
  server/src/main/java/seb40/main023/server/luckBag/exception/ExceptionCode.java
  server/src/main/java/seb40/main023/server/luckBag/repository/LuckBagRepository.java
  server/src/main/java/seb40/main023/server/luckBag/response/MultiResponseDto.java
  server/src/main/java/seb40/main023/server/luckBag/response/PageInfo.java
  server/src/main/java/seb40/main023/server/luckBag/response/SingleResponseDto.java
  server/src/main/java/seb40/main023/server/luckBag/service/LuckBagService.java
  server/src/main/resources/application.yml
  server/src/main/resources/static/docs/index.html
  server/src/test/java/seb40/main023/server/ServerApplicationTests.java
  server/src/test/java/seb40/main023/server/restdocs/LuckBag/LuckBagControllerRestDocsDelete.java
  server/src/test/java/seb40/main023/server/restdocs/LuckBag/LuckBagControllerRestDocsGet.java
  server/src/test/java/seb40/main023/server/restdocs/LuckBag/LuckBagControllerRestDocsGetAll.java
  server/src/test/java/seb40/main023/server/restdocs/LuckBag/LuckBagControllerRestDocsPatch.java
  server/src/test/java/seb40/main023/server/restdocs/LuckBag/LuckBagControllerRestDocsPost.java
  server/src/test/java/seb40/main023/server/util/ApiDocumentUtils.java
Labels: BE

#57 feat/#5 Rest docs member
  server/build.gradle
  server/gradlew
  server/src/main/java/seb40/main023/server/luckBag/controller/LuckBagController.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagPatchDto.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagPostDto.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagResponseDto.java
  server/src/main/java/seb40/main023/server/luckBag/entity/LuckBag.java
  server/src/main/java/seb40/main023/server/luckBag/mapper/LuckBagMapper.java
  server/src/main/java/seb40/main023/server/luckBag/service/LuckBagService.java
  server/src/main/java/seb40/main023/server/luckMango/controller/LuckMangoController.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoPatchDto.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoPostDto.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoResponseDto.java
  server/src/main/java/seb40/main023/server/luckMango/entity/LuckMango.java
  server/src/main/java/seb40/main023/server/luckMango/mapper/LuckMangoMapper.java
  server/src/main/java/seb40/main023/server/luckMango/service/LuckMangoService.java
  server/src/main/java/seb40/main023/server/member/controller/MemberController.java
  server/src/main/java/seb40/main023/server/member/dto/MemberPatchDto.java
  server/src/main/java/seb40/main023/server/member/dto/MemberPostDto.java
  server/src/main/java/seb40/main023/server/member/dto/MemberResponseDto.java
  server/src/main/java/seb40/main023/server/member/entity/Member.java
  server/src/main/java/seb40/main023/server/member/entity/MemberStatus.java
  server/src/main/java/seb40/main023/server/member/mapper/MemberMapper.java
  server/src/main/java/seb40/main023/server/member/service/MemberService.java
  server/src/main/java/seb40/main023/server/review/controller/ReviewController.java
  server/src/main/java/seb40/main023/server/review/dto/ReviewPatchDto.java
  server/src/main/java/seb40/main023/server/review/dto/ReviewPostDto.java
  server/src/main/java/seb40/main023/server/review/dto/ReviewResponseDto.java
  server/src/main/java/seb40/main023/server/review/entity/Review.java
  server/src/main/java/seb40/main023/server/review/mapper/ReviewMapper.java
  server/src/main/java/seb40/main023/server/review/service/ReviewService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/static/docs/index.html
  server/src/test/java/seb40/main023/server/restdocs/LuckBag/LuckBagControllerRestDocsDelete.java
  server/src/test/java/seb40/main023/server/restdocs/LuckBag/LuckBagControllerRestDocsGet.java
  server/src/test/java/seb40/main023/server/restdocs/LuckBag/LuckBagControllerRestDocsGetAll.java
  server/src/test/java/seb40/main023/server/restdocs/LuckBag/LuckBagControllerRestDocsPatch.java
  server/src/test/java/seb40/main023/server/restdocs/LuckBag/LuckBagControllerRestDocsPost.java
  server/src/test/java/seb40/main023/server/restdocs/luckMango/LuckMangoControllerRestDocsTest.java
  server/src/test/java/seb40/main023/server/restdocs/member/MemberControllerRestDocsTest.java
  server/src/test/java/seb40/main023/server/restdocs/review/ReviewControllerRestDocsTest.java
  server/src/test/java/seb40/main023/server/restdocs/util/ApiDocumentUtils.java
  server/src/test/java/seb40/main023/server/util/ApiDocumentUtils.java
Labels: BE

#54 feat/새해 복망고 페이지 추가 ui 구현
  client/components/Greeting.tsx
  client/components/ShareBtn.tsx
  client/constants/luckBagPos.ts
  client/package-lock.json
  client/package.json
  client/pages/edit/complete.tsx
  client/pages/lucky/index.tsx
  client/pages/lucky/login.tsx
  client/styles/globals.css
  client/tailwind.config.js
Labels: FE

#58 feat/RestDocs_Member
  server/src/docs/asciidoc/index.adoc
  server/src/docs/asciidoc/index.html
  server/src/main/java/seb40/main023/server/audit/Auditable.java
  server/src/main/java/seb40/main023/server/luckMango/service/LuckMangoService.java
  server/src/main/java/seb40/main023/server/member/controller/MemberController.java
  server/src/main/java/seb40/main023/server/member/dto/MemberPatchDto.java
  server/src/main/java/seb40/main023/server/member/dto/MemberResponseDto.java
  server/src/main/java/seb40/main023/server/member/entity/Member.java
  server/src/main/java/seb40/main023/server/member/entity/MemberStatus.java
  server/src/main/java/seb40/main023/server/member/service/MemberService.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/static/docs/index.html
  server/src/test/java/seb40/main023/server/restdocs/member/MemberControllerRestDocsTest.java
Labels: BE

#60 feat/덕담, 복망고 모달창 구현
  client/components/BokPreview.tsx
  client/components/Modal/EditModal.tsx
  client/components/Modal/LetterModal.tsx
  client/components/Modal/LongModal.tsx
  client/constants/luckBagOpt.ts
  client/pages/edit/index.tsx
  client/pages/lucky/index.tsx
  client/styles/globals.css
Labels: FE

#62 feat/메인 기능 구현 수정(업데이트)
  client/components/BokCard.tsx
  client/components/Footer.tsx
  client/components/main/Section.tsx
  client/components/main/chart/ServiceChart.tsx
  client/components/main/gallery/GalleryItem.tsx
  client/components/main/gallery/ServiceGallery.tsx
  client/components/main/review/ReviewItem.tsx
  client/components/main/review/ReviewSlide.tsx
  client/components/main/review/ReviewWrite.tsx
  client/components/main/review/ServiceReview.tsx
  client/components/sidebar.tsx
  client/components/userModify.tsx
  client/components/util/CountCharLength.tsx
  client/components/util/Loading.tsx
  client/components/util/Toast.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/mypage/index.tsx
  client/pages/test.tsx
  client/public/images/content/img-letter.png
  client/public/images/ico/ico-dropdown.svg
  client/public/images/ico/ico-info.svg
  client/public/images/ico/ico-slide-next.svg
  client/public/images/ico/ico-slide-prev.svg
  client/public/images/spinner.svg
  client/public/styles/aos-noscript.css
  client/styles/globals.css
Labels: feat, review request, FE

#67 feat/배경 이미지 업로드 기능 구현
  client/components/BokPreview.tsx
  client/components/Modal/EditModal.tsx
  client/components/header.tsx
  client/components/sidebar.tsx
  client/package-lock.json
  client/pages/edit/index.tsx
  client/pages/index.tsx
  client/pages/lucky/index.tsx
  client/styles/globals.css
Labels: FE

#70 feat/리뷰 슬라이드 패치 초기 세팅
  client/.gitignore
  client/api/useFetch.ts
  client/components/main/review/ServiceReview.tsx
  client/next.config.js
Labels: FE

#72 feat/유저정보수정 사진 기능 추가
  client/.gitignore
  client/components/Footer.tsx
  client/components/Modal/DefaultModal.tsx
  client/components/main/gallery/GalleryItem.tsx
  client/components/userModify.tsx
  client/package-lock.json
  client/pages/login/index.tsx
  client/pages/mypage/dummy.tsx
  client/pages/mypage/index.tsx
  client/pages/signup/index.tsx
  client/store/modalSlice.ts
  client/styles/globals.css
Labels: FE

#90 feat/mypage API 작업
  client/api/mypage.ts
  client/components/Header.tsx
  client/components/Sidebar.tsx
  client/components/main/gallery/GalleryItem.tsx
  client/components/main/howto/ServiceHowto.tsx
  client/components/main/info/ServiceIntro.tsx
  client/next.config.js
  client/pages/lucky/index.tsx
  client/pages/mypage/index.tsx
Labels: feat, FE

#96 feat/캡쳐 기능 추가
  client/api/mypage.ts
  client/components/main/gallery/GalleryItem.tsx
  client/package-lock.json
  client/package.json
  client/pages/create/index.tsx
  client/pages/edit/index.tsx
  client/pages/lucky/index.tsx
  client/pages/mypage/[memberId].tsx
  client/styles/globals.css
Labels: feat, FE

#99 Feat/로그인 기능 구현_JWT
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/docs/asciidoc/index.html
  server/src/main/java/seb40/main023/server/ServerApplication.java
  server/src/main/java/seb40/main023/server/audit/Auditable.java
  server/src/main/java/seb40/main023/server/exception/ExceptionCode.java
  server/src/main/java/seb40/main023/server/helper/event/MemberRegistrationApplicationEvent.java
  server/src/main/java/seb40/main023/server/luckBag/controller/LuckBagController.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagPatchDto.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagPostDto.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagResponseDto.java
  server/src/main/java/seb40/main023/server/luckBag/entity/LuckBag.java
  server/src/main/java/seb40/main023/server/luckBag/repository/LuckBagRepository.java
  server/src/main/java/seb40/main023/server/luckBag/service/LuckBagService.java
  server/src/main/java/seb40/main023/server/luckMango/controller/LuckMangoController.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoPatchDto.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoPostDto.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoResponseDto.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoResponseDto_Bag.java
  server/src/main/java/seb40/main023/server/luckMango/entity/LuckMango.java
  server/src/main/java/seb40/main023/server/luckMango/repository/LuckMangoRepository.java
  server/src/main/java/seb40/main023/server/luckMango/service/LuckMangoService.java
  server/src/main/java/seb40/main023/server/member/controller/MemberController.java
  server/src/main/java/seb40/main023/server/member/dto/MemberPatchDto.java
  server/src/main/java/seb40/main023/server/member/dto/MemberResponseDto.java
  server/src/main/java/seb40/main023/server/member/dto/MemberResponseDto_Mango.java
  server/src/main/java/seb40/main023/server/member/entity/Member.java
  server/src/main/java/seb40/main023/server/member/entity/MemberRole.java
  server/src/main/java/seb40/main023/server/member/entity/MemberStatus.java
  server/src/main/java/seb40/main023/server/member/mapper/MemberMapper.java
  server/src/main/java/seb40/main023/server/member/service/MemberService.java
  server/src/main/java/seb40/main023/server/review/controller/ReviewController.java
  server/src/main/java/seb40/main023/server/review/dto/ReviewResponseDto.java
  server/src/main/java/seb40/main023/server/review/service/ReviewService.java
  server/src/main/java/seb40/main023/server/security/auth/config/SecurityConfig.java
  server/src/main/java/seb40/main023/server/security/auth/dto/LoginDto.java
  server/src/main/java/seb40/main023/server/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/seb40/main023/server/security/auth/filter/JwtVerificationFilter.java
  server/src/main/java/seb40/main023/server/security/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/seb40/main023/server/security/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/seb40/main023/server/security/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/seb40/main023/server/security/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/seb40/main023/server/security/auth/jwt/JwtTokenizer.java
  server/src/main/java/seb40/main023/server/security/auth/service/MemberDetailsService.java
  server/src/main/java/seb40/main023/server/security/utils/CustomAuthorityUtils.java
  server/src/main/java/seb40/main023/server/security/utils/ErrorResponder.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/static/docs/index.html
  server/src/test/java/seb40/main023/server/restdocs/luckMango/LuckMangoControllerRestDocsTest.java
  server/src/test/java/seb40/main023/server/restdocs/member/MemberControllerRestDocsTest.java
  server/src/test/java/seb40/main023/server/restdocs/review/ReviewControllerRestDocsTest.java
Labels: BE

#98 feat/공유하기 기능 구현
  client/components/Banner.tsx
  client/components/BokPreview.tsx
  client/components/modals/DefaultModal.tsx
  client/components/modals/EditModal.tsx
  client/components/modals/LetterModal.tsx
  client/components/modals/LongModal.tsx
  client/components/modals/QrModal.tsx
  client/constants/templeteId.ts
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/create/index.tsx
  client/pages/edit/index.tsx
  client/pages/lucky/index.tsx
  client/pages/mypage/[memberId].tsx
  client/styles/globals.css
Labels: FE

#109 feat/로그인 기능 구현
  client/components/Header.tsx
  client/components/Sidebar.tsx
  client/components/main/gallery/ServiceGallery.tsx
  client/components/main/review/ReviewWrite.tsx
  client/components/main/review/ServiceReview.tsx
  client/components/modals/EditModal.tsx
  client/components/util/cookie/index.tsx
  client/fetch/create.ts
  client/fetch/login.ts
  client/fetch/lucky.ts
  client/fetch/mypage.ts
  client/fetch/review.ts
  client/fetch/signup.ts
  client/fetch/useFetch.ts
  client/package-lock.json
  client/package.json
  client/pages/api/auth/[...nextauth].ts
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/lucky/index.tsx
  client/pages/mypage/[memberId].tsx
  client/pages/signup/index.tsx
  client/store/loginSlice.ts
  client/store/store.ts
  client/types/login.ts
  client/types/signup.ts
Labels: feat, FE

#110 chore/authentication_접근 권한 수정
  server/src/main/java/seb40/main023/server/member/mapper/MemberMapper.java
  server/src/main/java/seb40/main023/server/security/auth/config/SecurityConfig.java
Labels: BE

#112 Feat/복망고 페이지 DF 작업중
  client/components/LuckBags.tsx
  client/components/modals/LetterModal.tsx
  client/components/modals/LongModal.tsx
  client/pages/lucky/[luckMangoId].tsx
  client/styles/globals.css
  client/types/mypage.ts
Labels: FE

#116 feat/RTK => Recoil 전환
  client/components/Header.tsx
  client/components/LuckBags.tsx
  client/components/Sidebar.tsx
  client/components/UserInfo.tsx
  client/components/lucky/Player.tsx
  client/components/modals/DefaultModal.tsx
  client/components/mypage/GalleryItem.tsx
  client/fetch/mypage.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/edit/[memberId].tsx
  client/pages/index.tsx
  client/pages/login/etc.tsx
  client/pages/login/index.tsx
  client/pages/lucky/[luckMangoId].tsx
  client/pages/mypage/[memberId].tsx
  client/pages/signup/index.tsx
  client/recoil/memberId.ts
  client/recoil/user.ts
  client/store/loginSlice.ts
  client/store/modalSlice.ts
  client/store/sidebarSlice.ts
  client/store/store.ts
Labels: feat, FE

#123 feat/mypage 동적라우팅 설정 및 로직 구현 완료
  client/components/Sidebar.tsx
  client/components/UserInfo.tsx
  client/components/modals/DefaultModal.tsx
  client/components/modals/DeleteMgModal.tsx
  client/components/modals/QrModal.tsx
  client/components/mypage/GalleryItem.tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/mypage/[memberId].tsx
  client/pages/signup/index.tsx
Labels: feat, FE

#125 BE/버그 수정
  server/build.gradle
  server/src/main/java/seb40/main023/server/Upload/Files.java
  server/src/main/java/seb40/main023/server/Upload/FilesController.java
  server/src/main/java/seb40/main023/server/Upload/FilesRepository.java
  server/src/main/java/seb40/main023/server/Upload/FilesService.java
  server/src/main/java/seb40/main023/server/Upload/controller/FilesController.java
  server/src/main/java/seb40/main023/server/Upload/dto/UpFilePatchDto.java
  server/src/main/java/seb40/main023/server/Upload/dto/UpFilePostDto.java
  server/src/main/java/seb40/main023/server/Upload/dto/UpFileResponse.java
  server/src/main/java/seb40/main023/server/Upload/entity/UpFile.java
  server/src/main/java/seb40/main023/server/Upload/mapper/UpFileMapper.java
  server/src/main/java/seb40/main023/server/Upload/repository/FilesRepository.java
  server/src/main/java/seb40/main023/server/Upload/service/FilesService.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagPostDto.java
  server/src/main/java/seb40/main023/server/luckBag/entity/LuckBag.java
  server/src/main/java/seb40/main023/server/luckBag/repository/LuckBagRepository.java
  server/src/main/java/seb40/main023/server/member/entity/Member.java
  server/src/main/resources/static/docs/index.html
Labels: BE
