Repository codestates-seb/seb40_main_023, pull requests merged in 2022-12, with the labels that each got.

#128 chore/하이드래이션 에러 핸들링
  client/components/Sidebar.tsx
  client/components/UserInfo.tsx
  client/components/modals/DefaultModal.tsx
  client/components/mypage/GalleryItem.tsx
  client/fetch/mypage.tsx
  client/next.config.js
  client/pages/create/complete.tsx
  client/pages/create/index.tsx
  client/pages/edit/[luckMangoId].tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/mypage/[memberId].tsx
  client/pages/signup/index.tsx
  client/recoil/memberId.ts
  client/recoil/user.ts
Labels: chore, FE

#133 feat/접근 제한, 공유하기 기능 수정
  client/components/LuckBags.tsx
  client/components/ShareBtn.tsx
  client/components/modals/CheckModal.tsx
  client/components/modals/EditModal.tsx
  client/components/modals/LetterModal.tsx
  client/components/modals/LongModal.tsx
  client/components/modals/QrModal.tsx
  client/components/mypage/GalleryItem.tsx
  client/next.config.js
  client/pages/404.tsx
  client/pages/create/complete.tsx
  client/pages/edit/[luckMangoId].tsx
  client/pages/edit/complete.tsx
  client/pages/lucky/[luckMangoId].tsx
  client/recoil/luckMgId.ts
  client/types/lucky.ts
Labels: FE

#137 fix/edit 페이지 리코일 값 수정
  client/pages/edit/[luckMangoId].tsx
Labels: FE

#143 feat/배경 이미지 업로드 기능 구현
  client/components/BokPreview.tsx
  client/components/modals/EditModal.tsx
  client/components/modals/LongModal.tsx
  client/fetch/create.ts
  client/pages/create/index.tsx
  client/pages/edit/[luckMangoId].tsx
  client/pages/lucky/[luckMangoId].tsx
  client/types/create.ts
  client/types/edit.ts
Labels: FE

#144 feat/유저 프로필 사진 수정 구현
  client/components/UserInfo.tsx
  client/components/mypage/GalleryItem.tsx
  client/next.config.js
  client/pages/mypage/[memberId].tsx
  client/tsconfig.json
Labels: feat, FE

#148 chore/링크 수정
  client/components/BokPreview.tsx
  client/components/mypage/GalleryItem.tsx
  client/pages/create/complete.tsx
  client/pages/edit/complete.tsx
  client/pages/lucky/[luckMangoId].tsx
Labels: FE

#175 fix/QA
  client/components/Header.tsx
  client/components/Sidebar.tsx
  client/components/UserInfo.tsx
  client/components/lucky/Player.tsx
  client/components/mypage/GalleryItem.tsx
  client/pages/create/index.tsx
  client/pages/login/index.tsx
  client/pages/lucky/[luckMangoId].tsx
  client/pages/mypage/[memberId].tsx
  client/pages/signup/index.tsx
Labels: bug, FE

#188 fix/session Storage 이동
  client/recoil/luckImg.ts
  client/recoil/luckMgId.ts
  client/recoil/memberId.ts
  client/recoil/memberName.ts
Labels: FE

#190 fix/갤러리 정렬 기능 구현 & API 경로 수정
  client/components/Sidebar.tsx
  client/components/UserInfo.tsx
  client/components/main/chart/ServiceChart.tsx
  client/components/main/gallery/ServiceGallery.tsx
  client/components/main/review/ReviewSlide.tsx
  client/components/modals/DefaultModal.tsx
  client/components/modals/DeleteMgModal.tsx
  client/components/mypage/GalleryItem.tsx
  client/fetch/create.ts
  client/fetch/edit.ts
  client/fetch/login.ts
  client/fetch/lucky.ts
  client/fetch/signup.ts
  client/fetch/useFetch.ts
  client/fetch/useGallery.ts
  client/pages/404.tsx
  client/pages/create/index.tsx
  client/pages/edit/[luckMangoId].tsx
  client/pages/login/etc.tsx
  client/pages/login/index.tsx
  client/pages/lucky/[luckMangoId].tsx
  client/pages/signup/index.tsx
  client/public/images/ico/ico-mypage-link.svg
  client/styles/globals.css
  client/tailwind.config.js
Labels: FE

#189 fix/공유하기 링크 수정
  client/components/mypage/GalleryItem.tsx
  client/pages/create/complete.tsx
  client/pages/edit/complete.tsx
  client/pages/lucky/[luckMangoId].tsx
  client/recoil/luckImg.ts
Labels: FE

#193 BE/sort 개선
  server/build.gradle
  server/src/main/java/seb40/main023/server/Upload/controller/UpFileController.java
  server/src/main/java/seb40/main023/server/Upload/repository/UpFileRepository.java
  server/src/main/java/seb40/main023/server/Upload/service/UpFileService.java
  server/src/main/java/seb40/main023/server/awsS3/config/AwsConfig.java
  server/src/main/java/seb40/main023/server/awsS3/controller/S3UpFileController.java
  server/src/main/java/seb40/main023/server/awsS3/dto/S3UpFileResponse.java
  server/src/main/java/seb40/main023/server/awsS3/entity/S3UpFile.java
  server/src/main/java/seb40/main023/server/awsS3/repository/S3UpFileRepository.java
  server/src/main/java/seb40/main023/server/awsS3/service/S3UpFileService.java
  server/src/main/java/seb40/main023/server/exception/ExceptionCode.java
  server/src/main/java/seb40/main023/server/luckBag/dto/LuckBagPatchDto.java
  server/src/main/java/seb40/main023/server/luckBag/service/LuckBagService.java
  server/src/main/java/seb40/main023/server/luckMango/controller/LuckMangoController.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoPatchDto.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoPostDto.java
  server/src/main/java/seb40/main023/server/luckMango/entity/LuckMango.java
  server/src/main/java/seb40/main023/server/luckMango/repository/LuckMangoRepository.java
  server/src/main/java/seb40/main023/server/luckMango/service/LuckMangoService.java
  server/src/main/java/seb40/main023/server/member/entity/Member.java
  server/src/main/java/seb40/main023/server/member/service/MemberService.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
  server/src/main/resources/static/docs/index.html
  server/src/test/java/seb40/main023/server/restdocs/luckMango/LuckMangoControllerRestDocsTest.java
Labels: BE

#195 fix/마이페이지 이미지 수정 에러 핸들링
  client/components/UserInfo.tsx
  client/pages/lucky/[luckMangoId].tsx
Labels: bug, FE

#197 Feat/log
  server/src/main/java/seb40/main023/server/awsS3/controller/S3UpFileController.java
  server/src/main/java/seb40/main023/server/log/aop/aop.java
  server/src/main/java/seb40/main023/server/log/config/WebMvcConfig.java
  server/src/main/java/seb40/main023/server/log/filter/RequestFilter.java
  server/src/main/java/seb40/main023/server/luckBag/service/LuckBagService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
  server/src/main/resources/logback/logback-server.xml
Labels: BE

#205 Fix/luck bag에 컬러,스타일pacth 안되던 버그 수정 / log에 membercreate uri만 받지 않게 수정
  server/src/main/java/seb40/main023/server/log/config/WebMvcConfig.java
  server/src/main/java/seb40/main023/server/log/filter/RequestFilter.java
  server/src/main/java/seb40/main023/server/luckBag/service/LuckBagService.java
  server/src/main/resources/logback/logback-server.xml
Labels: BE

#203 chore/쉬운 타입들 추가
  client/components/BokPreview.tsx
  client/components/Greeting.tsx
  client/components/Header.tsx
  client/components/LuckBags.tsx
  client/components/Sidebar.tsx
  client/components/UserInfo.tsx
  client/components/lucky/Player.tsx
  client/components/main/gallery/GalleryItem.tsx
  client/components/main/info/Countdown.tsx
  client/components/main/review/ReviewWrite.tsx
  client/components/modals/DefaultModal.tsx
  client/components/mypage/GalleryItem.tsx
  client/fetch/deleteUser.ts
  client/fetch/userInfo.ts
  client/pages/create/complete.tsx
  client/pages/create/index.tsx
  client/pages/edit/[luckMangoId].tsx
  client/pages/edit/complete.tsx
  client/pages/index.tsx
  client/pages/login/etc.tsx
  client/pages/login/index.tsx
  client/pages/lucky/[luckMangoId].tsx
  client/pages/mypage/[memberId].tsx
  client/pages/signup/index.tsx
Labels: chore, FE

#209 fix/이메일 중복 검사 기능 추가
  client/pages/signup/index.tsx
Labels: feat, FE

#239 feat/로그인 중복 확인 기능 추가
  client/pages/PwFind.tsx
  client/pages/login/index.tsx
  client/pages/signup/index.tsx
  client/styles/globals.css
Labels: feat, FE

#241 feat/비밀번호 찾기 기능 구현
  client/pages/PwFind.tsx
Labels: feat, FE

#242 서버 최종 버전 업데이트
  server/src/main/java/seb40/main023/server/awsS3/controller/S3UpFileController.java
  server/src/main/java/seb40/main023/server/awsS3/entity/S3UpFile.java
  server/src/main/java/seb40/main023/server/awsS3/service/S3UpFileService.java
  server/src/main/java/seb40/main023/server/exception/ExceptionCode.java
  server/src/main/java/seb40/main023/server/luckBag/controller/LuckBagController.java
  server/src/main/java/seb40/main023/server/luckBag/repository/LuckBagRepository.java
  server/src/main/java/seb40/main023/server/luckBag/service/LuckBagService.java
  server/src/main/java/seb40/main023/server/luckMango/controller/LuckMangoController.java
  server/src/main/java/seb40/main023/server/luckMango/dto/LuckMangoResponseDto.java
  server/src/main/java/seb40/main023/server/luckMango/entity/LuckMango.java
  server/src/main/java/seb40/main023/server/luckMango/repository/LuckMangoRepository.java
  server/src/main/java/seb40/main023/server/luckMango/service/LuckMangoService.java
  server/src/main/java/seb40/main023/server/member/controller/MemberController.java
  server/src/main/java/seb40/main023/server/member/entity/Member.java
  server/src/main/java/seb40/main023/server/member/service/MemberService.java
  server/src/main/java/seb40/main023/server/security/auth/config/SecurityConfig.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
Labels: BE
